/*
 * Licensed under the Apache License, Version 2.0 (the "License"); you may not use this file except
 * in compliance with the License. You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software distributed under the License
 * is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express
 * or implied. See the License for the specific language governing permissions and limitations under
 * the License.
 */
/*
 * This code was generated by https://code.google.com/p/google-apis-client-generator/
 * (build: 2014-11-17 18:43:33 UTC)
 * on 2015-01-10 at 02:56:28 UTC 
 * Modify at your own risk.
 */

package com.csgit.cao.model.communicationchannel.model;

/**
 * Model definition for AditivasDeductivas.
 *
 * <p> This is the Java data model class that specifies how to parse/serialize into the JSON that is
 * transmitted over HTTP when working with the communicationchannel. For a detailed explanation see:
 * <a href="http://code.google.com/p/google-http-java-client/wiki/JSON">http://code.google.com/p/google-http-java-client/wiki/JSON</a>
 * </p>
 *
 * @author Google, Inc.
 */
@SuppressWarnings("javadoc")
public final class AditivasDeductivas extends com.google.api.client.json.GenericJson {

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.lang.Double cantidad;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.lang.String fecha;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key("id_AditivasDeductivas") @com.google.api.client.json.JsonString
  private java.lang.Long idAditivasDeductivas;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key("id_Concepto") @com.google.api.client.json.JsonString
  private java.lang.Long idConcepto;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.lang.Integer tipoOperacion;

  /**
   * @return value or {@code null} for none
   */
  public java.lang.Double getCantidad() {
    return cantidad;
  }

  /**
   * @param cantidad cantidad or {@code null} for none
   */
  public AditivasDeductivas setCantidad(java.lang.Double cantidad) {
    this.cantidad = cantidad;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public java.lang.String getFecha() {
    return fecha;
  }

  /**
   * @param fecha fecha or {@code null} for none
   */
  public AditivasDeductivas setFecha(java.lang.String fecha) {
    this.fecha = fecha;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public java.lang.Long getIdAditivasDeductivas() {
    return idAditivasDeductivas;
  }

  /**
   * @param idAditivasDeductivas idAditivasDeductivas or {@code null} for none
   */
  public AditivasDeductivas setIdAditivasDeductivas(java.lang.Long idAditivasDeductivas) {
    this.idAditivasDeductivas = idAditivasDeductivas;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public java.lang.Long getIdConcepto() {
    return idConcepto;
  }

  /**
   * @param idConcepto idConcepto or {@code null} for none
   */
  public AditivasDeductivas setIdConcepto(java.lang.Long idConcepto) {
    this.idConcepto = idConcepto;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public java.lang.Integer getTipoOperacion() {
    return tipoOperacion;
  }

  /**
   * @param tipoOperacion tipoOperacion or {@code null} for none
   */
  public AditivasDeductivas setTipoOperacion(java.lang.Integer tipoOperacion) {
    this.tipoOperacion = tipoOperacion;
    return this;
  }

  @Override
  public AditivasDeductivas set(String fieldName, Object value) {
    return (AditivasDeductivas) super.set(fieldName, value);
  }

  @Override
  public AditivasDeductivas clone() {
    return (AditivasDeductivas) super.clone();
  }

}
