/*
 * Licensed under the Apache License, Version 2.0 (the "License"); you may not use this file except
 * in compliance with the License. You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software distributed under the License
 * is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express
 * or implied. See the License for the specific language governing permissions and limitations under
 * the License.
 */
/*
 * This code was generated by https://code.google.com/p/google-apis-client-generator/
 * (build: 2014-11-17 18:43:33 UTC)
 * on 2015-01-10 at 02:56:28 UTC 
 * Modify at your own risk.
 */

package com.csgit.cao.model.communicationchannel.model;

/**
 * Model definition for CatTipoEmpresa.
 *
 * <p> This is the Java data model class that specifies how to parse/serialize into the JSON that is
 * transmitted over HTTP when working with the communicationchannel. For a detailed explanation see:
 * <a href="http://code.google.com/p/google-http-java-client/wiki/JSON">http://code.google.com/p/google-http-java-client/wiki/JSON</a>
 * </p>
 *
 * @author Google, Inc.
 */
@SuppressWarnings("javadoc")
public final class CatTipoEmpresa extends com.google.api.client.json.GenericJson {

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.lang.String descipcion;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key("id_Tipo_Empresa") @com.google.api.client.json.JsonString
  private java.lang.Long idTipoEmpresa;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key("tipo_Empresa")
  private java.lang.String tipoEmpresa;

  /**
   * @return value or {@code null} for none
   */
  public java.lang.String getDescipcion() {
    return descipcion;
  }

  /**
   * @param descipcion descipcion or {@code null} for none
   */
  public CatTipoEmpresa setDescipcion(java.lang.String descipcion) {
    this.descipcion = descipcion;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public java.lang.Long getIdTipoEmpresa() {
    return idTipoEmpresa;
  }

  /**
   * @param idTipoEmpresa idTipoEmpresa or {@code null} for none
   */
  public CatTipoEmpresa setIdTipoEmpresa(java.lang.Long idTipoEmpresa) {
    this.idTipoEmpresa = idTipoEmpresa;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public java.lang.String getTipoEmpresa() {
    return tipoEmpresa;
  }

  /**
   * @param tipoEmpresa tipoEmpresa or {@code null} for none
   */
  public CatTipoEmpresa setTipoEmpresa(java.lang.String tipoEmpresa) {
    this.tipoEmpresa = tipoEmpresa;
    return this;
  }

  @Override
  public CatTipoEmpresa set(String fieldName, Object value) {
    return (CatTipoEmpresa) super.set(fieldName, value);
  }

  @Override
  public CatTipoEmpresa clone() {
    return (CatTipoEmpresa) super.clone();
  }

}
