/*
 * Licensed under the Apache License, Version 2.0 (the "License"); you may not use this file except
 * in compliance with the License. You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software distributed under the License
 * is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express
 * or implied. See the License for the specific language governing permissions and limitations under
 * the License.
 */
/*
 * This code was generated by https://code.google.com/p/google-apis-client-generator/
 * (build: 2014-11-17 18:43:33 UTC)
 * on 2015-01-10 at 02:56:28 UTC 
 * Modify at your own risk.
 */

package com.csgit.cao.model.communicationchannel.model;

/**
 * Model definition for CatTipoMaquinaria.
 *
 * <p> This is the Java data model class that specifies how to parse/serialize into the JSON that is
 * transmitted over HTTP when working with the communicationchannel. For a detailed explanation see:
 * <a href="http://code.google.com/p/google-http-java-client/wiki/JSON">http://code.google.com/p/google-http-java-client/wiki/JSON</a>
 * </p>
 *
 * @author Google, Inc.
 */
@SuppressWarnings("javadoc")
public final class CatTipoMaquinaria extends com.google.api.client.json.GenericJson {

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.lang.String descripcion;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key("id_tipo_Maquinaria") @com.google.api.client.json.JsonString
  private java.lang.Long idTipoMaquinaria;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key("tipo_Maquinaria")
  private java.lang.String tipoMaquinaria;

  /**
   * @return value or {@code null} for none
   */
  public java.lang.String getDescripcion() {
    return descripcion;
  }

  /**
   * @param descripcion descripcion or {@code null} for none
   */
  public CatTipoMaquinaria setDescripcion(java.lang.String descripcion) {
    this.descripcion = descripcion;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public java.lang.Long getIdTipoMaquinaria() {
    return idTipoMaquinaria;
  }

  /**
   * @param idTipoMaquinaria idTipoMaquinaria or {@code null} for none
   */
  public CatTipoMaquinaria setIdTipoMaquinaria(java.lang.Long idTipoMaquinaria) {
    this.idTipoMaquinaria = idTipoMaquinaria;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public java.lang.String getTipoMaquinaria() {
    return tipoMaquinaria;
  }

  /**
   * @param tipoMaquinaria tipoMaquinaria or {@code null} for none
   */
  public CatTipoMaquinaria setTipoMaquinaria(java.lang.String tipoMaquinaria) {
    this.tipoMaquinaria = tipoMaquinaria;
    return this;
  }

  @Override
  public CatTipoMaquinaria set(String fieldName, Object value) {
    return (CatTipoMaquinaria) super.set(fieldName, value);
  }

  @Override
  public CatTipoMaquinaria clone() {
    return (CatTipoMaquinaria) super.clone();
  }

}
