/*
 * Licensed under the Apache License, Version 2.0 (the "License"); you may not use this file except
 * in compliance with the License. You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software distributed under the License
 * is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express
 * or implied. See the License for the specific language governing permissions and limitations under
 * the License.
 */
/*
 * This code was generated by https://code.google.com/p/google-apis-client-generator/
 * (build: 2014-11-17 18:43:33 UTC)
 * on 2015-01-10 at 02:56:28 UTC 
 * Modify at your own risk.
 */

package com.csgit.cao.model.communicationchannel.model;

/**
 * Model definition for CatTipoPresona.
 *
 * <p> This is the Java data model class that specifies how to parse/serialize into the JSON that is
 * transmitted over HTTP when working with the communicationchannel. For a detailed explanation see:
 * <a href="http://code.google.com/p/google-http-java-client/wiki/JSON">http://code.google.com/p/google-http-java-client/wiki/JSON</a>
 * </p>
 *
 * @author Google, Inc.
 */
@SuppressWarnings("javadoc")
public final class CatTipoPresona extends com.google.api.client.json.GenericJson {

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.lang.String descipcion;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key("id_Tipo_Persona") @com.google.api.client.json.JsonString
  private java.lang.Long idTipoPersona;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key("tipo_Persona")
  private java.lang.String tipoPersona;

  /**
   * @return value or {@code null} for none
   */
  public java.lang.String getDescipcion() {
    return descipcion;
  }

  /**
   * @param descipcion descipcion or {@code null} for none
   */
  public CatTipoPresona setDescipcion(java.lang.String descipcion) {
    this.descipcion = descipcion;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public java.lang.Long getIdTipoPersona() {
    return idTipoPersona;
  }

  /**
   * @param idTipoPersona idTipoPersona or {@code null} for none
   */
  public CatTipoPresona setIdTipoPersona(java.lang.Long idTipoPersona) {
    this.idTipoPersona = idTipoPersona;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public java.lang.String getTipoPersona() {
    return tipoPersona;
  }

  /**
   * @param tipoPersona tipoPersona or {@code null} for none
   */
  public CatTipoPresona setTipoPersona(java.lang.String tipoPersona) {
    this.tipoPersona = tipoPersona;
    return this;
  }

  @Override
  public CatTipoPresona set(String fieldName, Object value) {
    return (CatTipoPresona) super.set(fieldName, value);
  }

  @Override
  public CatTipoPresona clone() {
    return (CatTipoPresona) super.clone();
  }

}
