/*
 * Licensed under the Apache License, Version 2.0 (the "License"); you may not use this file except
 * in compliance with the License. You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software distributed under the License
 * is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express
 * or implied. See the License for the specific language governing permissions and limitations under
 * the License.
 */
/*
 * This code was generated by https://code.google.com/p/google-apis-client-generator/
 * (build: 2014-11-17 18:43:33 UTC)
 * on 2015-01-10 at 02:56:28 UTC 
 * Modify at your own risk.
 */

package com.csgit.cao.model.communicationchannel.model;

/**
 * Model definition for Concepto.
 *
 * <p> This is the Java data model class that specifies how to parse/serialize into the JSON that is
 * transmitted over HTTP when working with the communicationchannel. For a detailed explanation see:
 * <a href="http://code.google.com/p/google-http-java-client/wiki/JSON">http://code.google.com/p/google-http-java-client/wiki/JSON</a>
 * </p>
 *
 * @author Google, Inc.
 */
@SuppressWarnings("javadoc")
public final class Concepto extends com.google.api.client.json.GenericJson {

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.lang.Double cantidadAvance;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.lang.Double cantidadTotal;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.lang.String clave;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private Text descripcion;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key("fecha_Fin")
  private java.lang.String fechaFin;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key("fecha_Inicio")
  private java.lang.String fechaInicio;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key("id_Concepto") @com.google.api.client.json.JsonString
  private java.lang.Long idConcepto;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key("id_Obra") @com.google.api.client.json.JsonString
  private java.lang.Long idObra;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.lang.Double importe;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key @com.google.api.client.json.JsonString
  private java.lang.Long padre;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.lang.Double precioUnitario;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.lang.String unidadMedida;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.lang.Boolean visible;

  /**
   * @return value or {@code null} for none
   */
  public java.lang.Double getCantidadAvance() {
    return cantidadAvance;
  }

  /**
   * @param cantidadAvance cantidadAvance or {@code null} for none
   */
  public Concepto setCantidadAvance(java.lang.Double cantidadAvance) {
    this.cantidadAvance = cantidadAvance;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public java.lang.Double getCantidadTotal() {
    return cantidadTotal;
  }

  /**
   * @param cantidadTotal cantidadTotal or {@code null} for none
   */
  public Concepto setCantidadTotal(java.lang.Double cantidadTotal) {
    this.cantidadTotal = cantidadTotal;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public java.lang.String getClave() {
    return clave;
  }

  /**
   * @param clave clave or {@code null} for none
   */
  public Concepto setClave(java.lang.String clave) {
    this.clave = clave;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public String getDescripcion() {
    return descripcion.getValue();
  }

  /**
   * @param descripcion descripcion or {@code null} for none
   */
  public Concepto setDescripcion(String descripcion) {
    this.descripcion = new Text().setValue(descripcion);
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public java.lang.String getFechaFin() {
    return fechaFin;
  }

  /**
   * @param fechaFin fechaFin or {@code null} for none
   */
  public Concepto setFechaFin(java.lang.String fechaFin) {
    this.fechaFin = fechaFin;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public java.lang.String getFechaInicio() {
    return fechaInicio;
  }

  /**
   * @param fechaInicio fechaInicio or {@code null} for none
   */
  public Concepto setFechaInicio(java.lang.String fechaInicio) {
    this.fechaInicio = fechaInicio;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public java.lang.Long getIdConcepto() {
    return idConcepto;
  }

  /**
   * @param idConcepto idConcepto or {@code null} for none
   */
  public Concepto setIdConcepto(java.lang.Long idConcepto) {
    this.idConcepto = idConcepto;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public java.lang.Long getIdObra() {
    return idObra;
  }

  /**
   * @param idObra idObra or {@code null} for none
   */
  public Concepto setIdObra(java.lang.Long idObra) {
    this.idObra = idObra;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public java.lang.Double getImporte() {
    return importe;
  }

  /**
   * @param importe importe or {@code null} for none
   */
  public Concepto setImporte(java.lang.Double importe) {
    this.importe = importe;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public java.lang.Long getPadre() {
    return padre;
  }

  /**
   * @param padre padre or {@code null} for none
   */
  public Concepto setPadre(java.lang.Long padre) {
    this.padre = padre;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public java.lang.Double getPrecioUnitario() {
    return precioUnitario;
  }

  /**
   * @param precioUnitario precioUnitario or {@code null} for none
   */
  public Concepto setPrecioUnitario(java.lang.Double precioUnitario) {
    this.precioUnitario = precioUnitario;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public java.lang.String getUnidadMedida() {
    return unidadMedida;
  }

  /**
   * @param unidadMedida unidadMedida or {@code null} for none
   */
  public Concepto setUnidadMedida(java.lang.String unidadMedida) {
    this.unidadMedida = unidadMedida;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public java.lang.Boolean getVisible() {
    return visible;
  }

  /**
   * @param visible visible or {@code null} for none
   */
  public Concepto setVisible(java.lang.Boolean visible) {
    this.visible = visible;
    return this;
  }

  @Override
  public Concepto set(String fieldName, Object value) {
    return (Concepto) super.set(fieldName, value);
  }

  @Override
  public Concepto clone() {
    return (Concepto) super.clone();
  }

}
