/*
 * Licensed under the Apache License, Version 2.0 (the "License"); you may not use this file except
 * in compliance with the License. You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software distributed under the License
 * is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express
 * or implied. See the License for the specific language governing permissions and limitations under
 * the License.
 */
/*
 * This code was generated by https://code.google.com/p/google-apis-client-generator/
 * (build: 2014-11-17 18:43:33 UTC)
 * on 2015-01-10 at 02:56:28 UTC 
 * Modify at your own risk.
 */

package com.csgit.cao.model.communicationchannel.model;

/**
 * Model definition for Directorio.
 *
 * <p> This is the Java data model class that specifies how to parse/serialize into the JSON that is
 * transmitted over HTTP when working with the communicationchannel. For a detailed explanation see:
 * <a href="http://code.google.com/p/google-http-java-client/wiki/JSON">http://code.google.com/p/google-http-java-client/wiki/JSON</a>
 * </p>
 *
 * @author Google, Inc.
 */
@SuppressWarnings("javadoc")
public final class Directorio extends com.google.api.client.json.GenericJson {

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.util.List<java.lang.String> arregloPersonasId;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key @com.google.api.client.json.JsonString
  private java.lang.Long idDirectorio;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key @com.google.api.client.json.JsonString
  private java.lang.Long idReferencia;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key @com.google.api.client.json.JsonString
  private java.lang.Long tipoReferencia;

  /**
   * @return value or {@code null} for none
   */
  public java.util.List<java.lang.String> getArregloPersonasId() {
    return arregloPersonasId;
  }

  /**
   * @param arregloPersonasId arregloPersonasId or {@code null} for none
   */
  public Directorio setArregloPersonasId(java.util.List<java.lang.String> arregloPersonasId) {
    this.arregloPersonasId = arregloPersonasId;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public java.lang.Long getIdDirectorio() {
    return idDirectorio;
  }

  /**
   * @param idDirectorio idDirectorio or {@code null} for none
   */
  public Directorio setIdDirectorio(java.lang.Long idDirectorio) {
    this.idDirectorio = idDirectorio;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public java.lang.Long getIdReferencia() {
    return idReferencia;
  }

  /**
   * @param idReferencia idReferencia or {@code null} for none
   */
  public Directorio setIdReferencia(java.lang.Long idReferencia) {
    this.idReferencia = idReferencia;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public java.lang.Long getTipoReferencia() {
    return tipoReferencia;
  }

  /**
   * @param tipoReferencia tipoReferencia or {@code null} for none
   */
  public Directorio setTipoReferencia(java.lang.Long tipoReferencia) {
    this.tipoReferencia = tipoReferencia;
    return this;
  }

  @Override
  public Directorio set(String fieldName, Object value) {
    return (Directorio) super.set(fieldName, value);
  }

  @Override
  public Directorio clone() {
    return (Directorio) super.clone();
  }

}
