/*
 * Licensed under the Apache License, Version 2.0 (the "License"); you may not use this file except
 * in compliance with the License. You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software distributed under the License
 * is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express
 * or implied. See the License for the specific language governing permissions and limitations under
 * the License.
 */
/*
 * This code was generated by https://code.google.com/p/google-apis-client-generator/
 * (build: 2014-11-17 18:43:33 UTC)
 * on 2015-01-10 at 02:56:28 UTC 
 * Modify at your own risk.
 */

package com.csgit.cao.model.communicationchannel.model;

/**
 * Model definition for DirectivoProyecto.
 *
 * <p> This is the Java data model class that specifies how to parse/serialize into the JSON that is
 * transmitted over HTTP when working with the communicationchannel. For a detailed explanation see:
 * <a href="http://code.google.com/p/google-http-java-client/wiki/JSON">http://code.google.com/p/google-http-java-client/wiki/JSON</a>
 * </p>
 *
 * @author Google, Inc.
 */
@SuppressWarnings("javadoc")
public final class DirectivoProyecto extends com.google.api.client.json.GenericJson {

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key @com.google.api.client.json.JsonString
  private java.lang.Long id;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key("id_directivo") @com.google.api.client.json.JsonString
  private java.lang.Long idDirectivo;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key("id_proyecto") @com.google.api.client.json.JsonString
  private java.lang.Long idProyecto;

  /**
   * @return value or {@code null} for none
   */
  public java.lang.Long getId() {
    return id;
  }

  /**
   * @param id id or {@code null} for none
   */
  public DirectivoProyecto setId(java.lang.Long id) {
    this.id = id;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public java.lang.Long getIdDirectivo() {
    return idDirectivo;
  }

  /**
   * @param idDirectivo idDirectivo or {@code null} for none
   */
  public DirectivoProyecto setIdDirectivo(java.lang.Long idDirectivo) {
    this.idDirectivo = idDirectivo;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public java.lang.Long getIdProyecto() {
    return idProyecto;
  }

  /**
   * @param idProyecto idProyecto or {@code null} for none
   */
  public DirectivoProyecto setIdProyecto(java.lang.Long idProyecto) {
    this.idProyecto = idProyecto;
    return this;
  }

  @Override
  public DirectivoProyecto set(String fieldName, Object value) {
    return (DirectivoProyecto) super.set(fieldName, value);
  }

  @Override
  public DirectivoProyecto clone() {
    return (DirectivoProyecto) super.clone();
  }

}
