/*
 * Licensed under the Apache License, Version 2.0 (the "License"); you may not use this file except
 * in compliance with the License. You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software distributed under the License
 * is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express
 * or implied. See the License for the specific language governing permissions and limitations under
 * the License.
 */
/*
 * This code was generated by https://code.google.com/p/google-apis-client-generator/
 * (build: 2014-11-17 18:43:33 UTC)
 * on 2015-01-10 at 02:56:28 UTC 
 * Modify at your own risk.
 */

package com.csgit.cao.model.communicationchannel.model;

/**
 * Model definition for Empresa.
 *
 * <p> This is the Java data model class that specifies how to parse/serialize into the JSON that is
 * transmitted over HTTP when working with the communicationchannel. For a detailed explanation see:
 * <a href="http://code.google.com/p/google-http-java-client/wiki/JSON">http://code.google.com/p/google-http-java-client/wiki/JSON</a>
 * </p>
 *
 * @author Google, Inc.
 */
@SuppressWarnings("javadoc")
public final class Empresa extends com.google.api.client.json.GenericJson {

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.lang.String calle;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key("codi_Postal")
  private java.lang.Integer codiPostal;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.lang.String colonia;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key("del_o_Mun")
  private java.lang.String delOMun;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.lang.String entidad;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key("id_Empresa") @com.google.api.client.json.JsonString
  private java.lang.Long idEmpresa;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key("id_tipo_empresa") @com.google.api.client.json.JsonString
  private java.lang.Long idTipoEmpresa;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.lang.String imss;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.lang.String logo;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.lang.String nombre;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key("num_Ext")
  private java.lang.String numExt;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key("num_Int")
  private java.lang.String numInt;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.lang.String rfc;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.lang.String siglas;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.lang.Boolean visible;

  /**
   * @return value or {@code null} for none
   */
  public java.lang.String getCalle() {
    return calle;
  }

  /**
   * @param calle calle or {@code null} for none
   */
  public Empresa setCalle(java.lang.String calle) {
    this.calle = calle;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public java.lang.Integer getCodiPostal() {
    return codiPostal;
  }

  /**
   * @param codiPostal codiPostal or {@code null} for none
   */
  public Empresa setCodiPostal(java.lang.Integer codiPostal) {
    this.codiPostal = codiPostal;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public java.lang.String getColonia() {
    return colonia;
  }

  /**
   * @param colonia colonia or {@code null} for none
   */
  public Empresa setColonia(java.lang.String colonia) {
    this.colonia = colonia;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public java.lang.String getDelOMun() {
    return delOMun;
  }

  /**
   * @param delOMun delOMun or {@code null} for none
   */
  public Empresa setDelOMun(java.lang.String delOMun) {
    this.delOMun = delOMun;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public java.lang.String getEntidad() {
    return entidad;
  }

  /**
   * @param entidad entidad or {@code null} for none
   */
  public Empresa setEntidad(java.lang.String entidad) {
    this.entidad = entidad;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public java.lang.Long getIdEmpresa() {
    return idEmpresa;
  }

  /**
   * @param idEmpresa idEmpresa or {@code null} for none
   */
  public Empresa setIdEmpresa(java.lang.Long idEmpresa) {
    this.idEmpresa = idEmpresa;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public java.lang.Long getIdTipoEmpresa() {
    return idTipoEmpresa;
  }

  /**
   * @param idTipoEmpresa idTipoEmpresa or {@code null} for none
   */
  public Empresa setIdTipoEmpresa(java.lang.Long idTipoEmpresa) {
    this.idTipoEmpresa = idTipoEmpresa;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public java.lang.String getImss() {
    return imss;
  }

  /**
   * @param imss imss or {@code null} for none
   */
  public Empresa setImss(java.lang.String imss) {
    this.imss = imss;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public java.lang.String getLogo() {
    return logo;
  }

  /**
   * @param logo logo or {@code null} for none
   */
  public Empresa setLogo(java.lang.String logo) {
    this.logo = logo;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public java.lang.String getNombre() {
    return nombre;
  }

  /**
   * @param nombre nombre or {@code null} for none
   */
  public Empresa setNombre(java.lang.String nombre) {
    this.nombre = nombre;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public java.lang.String getNumExt() {
    return numExt;
  }

  /**
   * @param numExt numExt or {@code null} for none
   */
  public Empresa setNumExt(java.lang.String numExt) {
    this.numExt = numExt;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public java.lang.String getNumInt() {
    return numInt;
  }

  /**
   * @param numInt numInt or {@code null} for none
   */
  public Empresa setNumInt(java.lang.String numInt) {
    this.numInt = numInt;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public java.lang.String getRfc() {
    return rfc;
  }

  /**
   * @param rfc rfc or {@code null} for none
   */
  public Empresa setRfc(java.lang.String rfc) {
    this.rfc = rfc;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public java.lang.String getSiglas() {
    return siglas;
  }

  /**
   * @param siglas siglas or {@code null} for none
   */
  public Empresa setSiglas(java.lang.String siglas) {
    this.siglas = siglas;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public java.lang.Boolean getVisible() {
    return visible;
  }

  /**
   * @param visible visible or {@code null} for none
   */
  public Empresa setVisible(java.lang.Boolean visible) {
    this.visible = visible;
    return this;
  }

  @Override
  public Empresa set(String fieldName, Object value) {
    return (Empresa) super.set(fieldName, value);
  }

  @Override
  public Empresa clone() {
    return (Empresa) super.clone();
  }

}
