/*
 * Licensed under the Apache License, Version 2.0 (the "License"); you may not use this file except
 * in compliance with the License. You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software distributed under the License
 * is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express
 * or implied. See the License for the specific language governing permissions and limitations under
 * the License.
 */
/*
 * This code was generated by https://code.google.com/p/google-apis-client-generator/
 * (build: 2014-11-17 18:43:33 UTC)
 * on 2015-01-10 at 02:56:28 UTC 
 * Modify at your own risk.
 */

package com.csgit.cao.model.communicationchannel.model;

/**
 * Model definition for Estimacion.
 *
 * <p> This is the Java data model class that specifies how to parse/serialize into the JSON that is
 * transmitted over HTTP when working with the communicationchannel. For a detailed explanation see:
 * <a href="http://code.google.com/p/google-http-java-client/wiki/JSON">http://code.google.com/p/google-http-java-client/wiki/JSON</a>
 * </p>
 *
 * @author Google, Inc.
 */
@SuppressWarnings("javadoc")
public final class Estimacion extends com.google.api.client.json.GenericJson {

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key @com.google.api.client.json.JsonString
  private java.lang.Long cantidadAutorizada;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.lang.String email;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key @com.google.api.client.json.JsonString
  private java.lang.Long estimacion;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.lang.String fechaEstimacion;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.lang.String fechaFin;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.lang.String fechaInicio;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key @com.google.api.client.json.JsonString
  private java.lang.Long idConcepto;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key @com.google.api.client.json.JsonString
  private java.lang.Long idObra;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key("id_Estimacion") @com.google.api.client.json.JsonString
  private java.lang.Long idEstimacion;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key("id_dispo") @com.google.api.client.json.JsonString
  private java.lang.Long idDispo;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key @com.google.api.client.json.JsonString
  private java.lang.Long numero;

  /**
   * @return value or {@code null} for none
   */
  public java.lang.Long getCantidadAutorizada() {
    return cantidadAutorizada;
  }

  /**
   * @param cantidadAutorizada cantidadAutorizada or {@code null} for none
   */
  public Estimacion setCantidadAutorizada(java.lang.Long cantidadAutorizada) {
    this.cantidadAutorizada = cantidadAutorizada;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public java.lang.String getEmail() {
    return email;
  }

  /**
   * @param email email or {@code null} for none
   */
  public Estimacion setEmail(java.lang.String email) {
    this.email = email;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public java.lang.Long getEstimacion() {
    return estimacion;
  }

  /**
   * @param estimacion estimacion or {@code null} for none
   */
  public Estimacion setEstimacion(java.lang.Long estimacion) {
    this.estimacion = estimacion;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public java.lang.String getFechaEstimacion() {
    return fechaEstimacion;
  }

  /**
   * @param fechaEstimacion fechaEstimacion or {@code null} for none
   */
  public Estimacion setFechaEstimacion(java.lang.String fechaEstimacion) {
    this.fechaEstimacion = fechaEstimacion;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public java.lang.String getFechaFin() {
    return fechaFin;
  }

  /**
   * @param fechaFin fechaFin or {@code null} for none
   */
  public Estimacion setFechaFin(java.lang.String fechaFin) {
    this.fechaFin = fechaFin;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public java.lang.String getFechaInicio() {
    return fechaInicio;
  }

  /**
   * @param fechaInicio fechaInicio or {@code null} for none
   */
  public Estimacion setFechaInicio(java.lang.String fechaInicio) {
    this.fechaInicio = fechaInicio;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public java.lang.Long getIdConcepto() {
    return idConcepto;
  }

  /**
   * @param idConcepto idConcepto or {@code null} for none
   */
  public Estimacion setIdConcepto(java.lang.Long idConcepto) {
    this.idConcepto = idConcepto;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public java.lang.Long getIdObra() {
    return idObra;
  }

  /**
   * @param idObra idObra or {@code null} for none
   */
  public Estimacion setIdObra(java.lang.Long idObra) {
    this.idObra = idObra;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public java.lang.Long getIdEstimacion() {
    return idEstimacion;
  }

  /**
   * @param idEstimacion idEstimacion or {@code null} for none
   */
  public Estimacion setIdEstimacion(java.lang.Long idEstimacion) {
    this.idEstimacion = idEstimacion;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public java.lang.Long getIdDispo() {
    return idDispo;
  }

  /**
   * @param idDispo idDispo or {@code null} for none
   */
  public Estimacion setIdDispo(java.lang.Long idDispo) {
    this.idDispo = idDispo;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public java.lang.Long getNumero() {
    return numero;
  }

  /**
   * @param numero numero or {@code null} for none
   */
  public Estimacion setNumero(java.lang.Long numero) {
    this.numero = numero;
    return this;
  }

  @Override
  public Estimacion set(String fieldName, Object value) {
    return (Estimacion) super.set(fieldName, value);
  }

  @Override
  public Estimacion clone() {
    return (Estimacion) super.clone();
  }

}
