/*
 * Licensed under the Apache License, Version 2.0 (the "License"); you may not use this file except
 * in compliance with the License. You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software distributed under the License
 * is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express
 * or implied. See the License for the specific language governing permissions and limitations under
 * the License.
 */
/*
 * This code was generated by https://code.google.com/p/google-apis-client-generator/
 * (build: 2014-11-17 18:43:33 UTC)
 * on 2015-01-10 at 02:56:28 UTC 
 * Modify at your own risk.
 */

package com.csgit.cao.model.communicationchannel.model;

/**
 * Model definition for Maquinaria.
 *
 * <p> This is the Java data model class that specifies how to parse/serialize into the JSON that is
 * transmitted over HTTP when working with the communicationchannel. For a detailed explanation see:
 * <a href="http://code.google.com/p/google-http-java-client/wiki/JSON">http://code.google.com/p/google-http-java-client/wiki/JSON</a>
 * </p>
 *
 * @author Google, Inc.
 */
@SuppressWarnings("javadoc")
public final class Maquinaria extends com.google.api.client.json.GenericJson {

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.lang.String descripcion;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key @com.google.api.client.json.JsonString
  private java.lang.Long familia;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key("id_Familia") @com.google.api.client.json.JsonString
  private java.lang.Long idFamilia;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key("id_Maquinaria") @com.google.api.client.json.JsonString
  private java.lang.Long idMaquinaria;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key("id_tipo_Maquinaria") @com.google.api.client.json.JsonString
  private java.lang.Long idTipoMaquinaria;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.lang.String nombre;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key("path_Imagen")
  private java.lang.String pathImagen;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.lang.Boolean visible;

  /**
   * @return value or {@code null} for none
   */
  public java.lang.String getDescripcion() {
    return descripcion;
  }

  /**
   * @param descripcion descripcion or {@code null} for none
   */
  public Maquinaria setDescripcion(java.lang.String descripcion) {
    this.descripcion = descripcion;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public java.lang.Long getFamilia() {
    return familia;
  }

  /**
   * @param familia familia or {@code null} for none
   */
  public Maquinaria setFamilia(java.lang.Long familia) {
    this.familia = familia;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public java.lang.Long getIdFamilia() {
    return idFamilia;
  }

  /**
   * @param idFamilia idFamilia or {@code null} for none
   */
  public Maquinaria setIdFamilia(java.lang.Long idFamilia) {
    this.idFamilia = idFamilia;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public java.lang.Long getIdMaquinaria() {
    return idMaquinaria;
  }

  /**
   * @param idMaquinaria idMaquinaria or {@code null} for none
   */
  public Maquinaria setIdMaquinaria(java.lang.Long idMaquinaria) {
    this.idMaquinaria = idMaquinaria;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public java.lang.Long getIdTipoMaquinaria() {
    return idTipoMaquinaria;
  }

  /**
   * @param idTipoMaquinaria idTipoMaquinaria or {@code null} for none
   */
  public Maquinaria setIdTipoMaquinaria(java.lang.Long idTipoMaquinaria) {
    this.idTipoMaquinaria = idTipoMaquinaria;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public java.lang.String getNombre() {
    return nombre;
  }

  /**
   * @param nombre nombre or {@code null} for none
   */
  public Maquinaria setNombre(java.lang.String nombre) {
    this.nombre = nombre;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public java.lang.String getPathImagen() {
    return pathImagen;
  }

  /**
   * @param pathImagen pathImagen or {@code null} for none
   */
  public Maquinaria setPathImagen(java.lang.String pathImagen) {
    this.pathImagen = pathImagen;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public java.lang.Boolean getVisible() {
    return visible;
  }

  /**
   * @param visible visible or {@code null} for none
   */
  public Maquinaria setVisible(java.lang.Boolean visible) {
    this.visible = visible;
    return this;
  }

  @Override
  public Maquinaria set(String fieldName, Object value) {
    return (Maquinaria) super.set(fieldName, value);
  }

  @Override
  public Maquinaria clone() {
    return (Maquinaria) super.clone();
  }

}
