/*
 * Licensed under the Apache License, Version 2.0 (the "License"); you may not use this file except
 * in compliance with the License. You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software distributed under the License
 * is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express
 * or implied. See the License for the specific language governing permissions and limitations under
 * the License.
 */
/*
 * This code was generated by https://code.google.com/p/google-apis-client-generator/
 * (build: 2014-11-17 18:43:33 UTC)
 * on 2015-01-10 at 02:56:28 UTC 
 * Modify at your own risk.
 */

package com.csgit.cao.model.communicationchannel.model;

/**
 * Model definition for Multimedia.
 *
 * <p> This is the Java data model class that specifies how to parse/serialize into the JSON that is
 * transmitted over HTTP when working with the communicationchannel. For a detailed explanation see:
 * <a href="http://code.google.com/p/google-http-java-client/wiki/JSON">http://code.google.com/p/google-http-java-client/wiki/JSON</a>
 * </p>
 *
 * @author Google, Inc.
 */
@SuppressWarnings("javadoc")
public final class Multimedia extends com.google.api.client.json.GenericJson {

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.lang.String descripcion;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.lang.String fecha;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key @com.google.api.client.json.JsonString
  private java.lang.Long formato;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key @com.google.api.client.json.JsonString
  private java.lang.Long idMultimedia;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key @com.google.api.client.json.JsonString
  private java.lang.Long idReferencia;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.lang.String path;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.lang.Integer tipoArchivo;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.lang.Integer tipoReferencia;

  /**
   * @return value or {@code null} for none
   */
  public java.lang.String getDescripcion() {
    return descripcion;
  }

  /**
   * @param descripcion descripcion or {@code null} for none
   */
  public Multimedia setDescripcion(java.lang.String descripcion) {
    this.descripcion = descripcion;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public java.lang.String getFecha() {
    return fecha;
  }

  /**
   * @param fecha fecha or {@code null} for none
   */
  public Multimedia setFecha(java.lang.String fecha) {
    this.fecha = fecha;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public java.lang.Long getFormato() {
    return formato;
  }

  /**
   * @param formato formato or {@code null} for none
   */
  public Multimedia setFormato(java.lang.Long formato) {
    this.formato = formato;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public java.lang.Long getIdMultimedia() {
    return idMultimedia;
  }

  /**
   * @param idMultimedia idMultimedia or {@code null} for none
   */
  public Multimedia setIdMultimedia(java.lang.Long idMultimedia) {
    this.idMultimedia = idMultimedia;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public java.lang.Long getIdReferencia() {
    return idReferencia;
  }

  /**
   * @param idReferencia idReferencia or {@code null} for none
   */
  public Multimedia setIdReferencia(java.lang.Long idReferencia) {
    this.idReferencia = idReferencia;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public java.lang.String getPath() {
    return path;
  }

  /**
   * @param path path or {@code null} for none
   */
  public Multimedia setPath(java.lang.String path) {
    this.path = path;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public java.lang.Integer getTipoArchivo() {
    return tipoArchivo;
  }

  /**
   * @param tipoArchivo tipoArchivo or {@code null} for none
   */
  public Multimedia setTipoArchivo(java.lang.Integer tipoArchivo) {
    this.tipoArchivo = tipoArchivo;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public java.lang.Integer getTipoReferencia() {
    return tipoReferencia;
  }

  /**
   * @param tipoReferencia tipoReferencia or {@code null} for none
   */
  public Multimedia setTipoReferencia(java.lang.Integer tipoReferencia) {
    this.tipoReferencia = tipoReferencia;
    return this;
  }

  @Override
  public Multimedia set(String fieldName, Object value) {
    return (Multimedia) super.set(fieldName, value);
  }

  @Override
  public Multimedia clone() {
    return (Multimedia) super.clone();
  }

}
