/*
 * Licensed under the Apache License, Version 2.0 (the "License"); you may not use this file except
 * in compliance with the License. You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software distributed under the License
 * is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express
 * or implied. See the License for the specific language governing permissions and limitations under
 * the License.
 */
/*
 * This code was generated by https://code.google.com/p/google-apis-client-generator/
 * (build: 2014-11-17 18:43:33 UTC)
 * on 2015-01-10 at 02:56:28 UTC 
 * Modify at your own risk.
 */

package com.csgit.cao.model.communicationchannel.model;

/**
 * Model definition for OrgGoubernamental.
 *
 * <p> This is the Java data model class that specifies how to parse/serialize into the JSON that is
 * transmitted over HTTP when working with the communicationchannel. For a detailed explanation see:
 * <a href="http://code.google.com/p/google-http-java-client/wiki/JSON">http://code.google.com/p/google-http-java-client/wiki/JSON</a>
 * </p>
 *
 * @author Google, Inc.
 */
@SuppressWarnings("javadoc")
public final class OrgGoubernamental extends com.google.api.client.json.GenericJson {

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key("id_Organizacion") @com.google.api.client.json.JsonString
  private java.lang.Long idOrganizacion;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.lang.String logotipo;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key("nombre_Oficial")
  private java.lang.String nombreOficial;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key("nombre_corto")
  private java.lang.String nombreCorto;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key("sitio_Web")
  private java.lang.String sitioWeb;

  /**
   * @return value or {@code null} for none
   */
  public java.lang.Long getIdOrganizacion() {
    return idOrganizacion;
  }

  /**
   * @param idOrganizacion idOrganizacion or {@code null} for none
   */
  public OrgGoubernamental setIdOrganizacion(java.lang.Long idOrganizacion) {
    this.idOrganizacion = idOrganizacion;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public java.lang.String getLogotipo() {
    return logotipo;
  }

  /**
   * @param logotipo logotipo or {@code null} for none
   */
  public OrgGoubernamental setLogotipo(java.lang.String logotipo) {
    this.logotipo = logotipo;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public java.lang.String getNombreOficial() {
    return nombreOficial;
  }

  /**
   * @param nombreOficial nombreOficial or {@code null} for none
   */
  public OrgGoubernamental setNombreOficial(java.lang.String nombreOficial) {
    this.nombreOficial = nombreOficial;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public java.lang.String getNombreCorto() {
    return nombreCorto;
  }

  /**
   * @param nombreCorto nombreCorto or {@code null} for none
   */
  public OrgGoubernamental setNombreCorto(java.lang.String nombreCorto) {
    this.nombreCorto = nombreCorto;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public java.lang.String getSitioWeb() {
    return sitioWeb;
  }

  /**
   * @param sitioWeb sitioWeb or {@code null} for none
   */
  public OrgGoubernamental setSitioWeb(java.lang.String sitioWeb) {
    this.sitioWeb = sitioWeb;
    return this;
  }

  @Override
  public OrgGoubernamental set(String fieldName, Object value) {
    return (OrgGoubernamental) super.set(fieldName, value);
  }

  @Override
  public OrgGoubernamental clone() {
    return (OrgGoubernamental) super.clone();
  }

}
