/*
 * Licensed under the Apache License, Version 2.0 (the "License"); you may not use this file except
 * in compliance with the License. You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software distributed under the License
 * is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express
 * or implied. See the License for the specific language governing permissions and limitations under
 * the License.
 */
/*
 * This code was generated by https://code.google.com/p/google-apis-client-generator/
 * (build: 2014-11-17 18:43:33 UTC)
 * on 2015-01-10 at 02:56:28 UTC 
 * Modify at your own risk.
 */

package com.csgit.cao.model.communicationchannel.model;

/**
 * Model definition for Programa.
 *
 * <p> This is the Java data model class that specifies how to parse/serialize into the JSON that is
 * transmitted over HTTP when working with the communicationchannel. For a detailed explanation see:
 * <a href="http://code.google.com/p/google-http-java-client/wiki/JSON">http://code.google.com/p/google-http-java-client/wiki/JSON</a>
 * </p>
 *
 * @author Google, Inc.
 */
@SuppressWarnings("javadoc")
public final class Programa extends com.google.api.client.json.GenericJson {

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.lang.String fecha;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key("id_programa") @com.google.api.client.json.JsonString
  private java.lang.Long idPrograma;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key("id_referencia") @com.google.api.client.json.JsonString
  private java.lang.Long idReferencia;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key("porcentaje_avance")
  private java.lang.Double porcentajeAvance;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key("tipo_avance")
  private java.lang.Integer tipoAvance;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key("tipo_entidad")
  private java.lang.Integer tipoEntidad;

  /**
   * @return value or {@code null} for none
   */
  public java.lang.String getFecha() {
    return fecha;
  }

  /**
   * @param fecha fecha or {@code null} for none
   */
  public Programa setFecha(java.lang.String fecha) {
    this.fecha = fecha;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public java.lang.Long getIdPrograma() {
    return idPrograma;
  }

  /**
   * @param idPrograma idPrograma or {@code null} for none
   */
  public Programa setIdPrograma(java.lang.Long idPrograma) {
    this.idPrograma = idPrograma;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public java.lang.Long getIdReferencia() {
    return idReferencia;
  }

  /**
   * @param idReferencia idReferencia or {@code null} for none
   */
  public Programa setIdReferencia(java.lang.Long idReferencia) {
    this.idReferencia = idReferencia;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public java.lang.Double getPorcentajeAvance() {
    return porcentajeAvance;
  }

  /**
   * @param porcentajeAvance porcentajeAvance or {@code null} for none
   */
  public Programa setPorcentajeAvance(java.lang.Double porcentajeAvance) {
    this.porcentajeAvance = porcentajeAvance;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public java.lang.Integer getTipoAvance() {
    return tipoAvance;
  }

  /**
   * @param tipoAvance tipoAvance or {@code null} for none
   */
  public Programa setTipoAvance(java.lang.Integer tipoAvance) {
    this.tipoAvance = tipoAvance;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public java.lang.Integer getTipoEntidad() {
    return tipoEntidad;
  }

  /**
   * @param tipoEntidad tipoEntidad or {@code null} for none
   */
  public Programa setTipoEntidad(java.lang.Integer tipoEntidad) {
    this.tipoEntidad = tipoEntidad;
    return this;
  }

  @Override
  public Programa set(String fieldName, Object value) {
    return (Programa) super.set(fieldName, value);
  }

  @Override
  public Programa clone() {
    return (Programa) super.clone();
  }

}
