/*
 * Licensed under the Apache License, Version 2.0 (the "License"); you may not use this file except
 * in compliance with the License. You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software distributed under the License
 * is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express
 * or implied. See the License for the specific language governing permissions and limitations under
 * the License.
 */
/*
 * This code was generated by https://code.google.com/p/google-apis-client-generator/
 * (build: 2014-11-17 18:43:33 UTC)
 * on 2015-01-10 at 02:56:28 UTC 
 * Modify at your own risk.
 */

package com.csgit.cao.model.communicationchannel.model;

/**
 * Model definition for Proyecto.
 *
 * <p> This is the Java data model class that specifies how to parse/serialize into the JSON that is
 * transmitted over HTTP when working with the communicationchannel. For a detailed explanation see:
 * <a href="http://code.google.com/p/google-http-java-client/wiki/JSON">http://code.google.com/p/google-http-java-client/wiki/JSON</a>
 * </p>
 *
 * @author Google, Inc.
 */
@SuppressWarnings("javadoc")
public final class Proyecto extends com.google.api.client.json.GenericJson {

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.lang.String descripcion;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key("id_Proyecto") @com.google.api.client.json.JsonString
  private java.lang.Long idProyecto;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key("id_dependencia") @com.google.api.client.json.JsonString
  private java.lang.Long idDependencia;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key("id_secretaria") @com.google.api.client.json.JsonString
  private java.lang.Long idSecretaria;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key("id_ubicacion") @com.google.api.client.json.JsonString
  private java.lang.Long idUbicacion;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key("nombre_corto")
  private java.lang.String nombreCorto;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key("nombre_largo")
  private java.lang.String nombreLargo;

  /**
   * @return value or {@code null} for none
   */
  public java.lang.String getDescripcion() {
    return descripcion;
  }

  /**
   * @param descripcion descripcion or {@code null} for none
   */
  public Proyecto setDescripcion(java.lang.String descripcion) {
    this.descripcion = descripcion;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public java.lang.Long getIdProyecto() {
    return idProyecto;
  }

  /**
   * @param idProyecto idProyecto or {@code null} for none
   */
  public Proyecto setIdProyecto(java.lang.Long idProyecto) {
    this.idProyecto = idProyecto;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public java.lang.Long getIdDependencia() {
    return idDependencia;
  }

  /**
   * @param idDependencia idDependencia or {@code null} for none
   */
  public Proyecto setIdDependencia(java.lang.Long idDependencia) {
    this.idDependencia = idDependencia;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public java.lang.Long getIdSecretaria() {
    return idSecretaria;
  }

  /**
   * @param idSecretaria idSecretaria or {@code null} for none
   */
  public Proyecto setIdSecretaria(java.lang.Long idSecretaria) {
    this.idSecretaria = idSecretaria;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public java.lang.Long getIdUbicacion() {
    return idUbicacion;
  }

  /**
   * @param idUbicacion idUbicacion or {@code null} for none
   */
  public Proyecto setIdUbicacion(java.lang.Long idUbicacion) {
    this.idUbicacion = idUbicacion;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public java.lang.String getNombreCorto() {
    return nombreCorto;
  }

  /**
   * @param nombreCorto nombreCorto or {@code null} for none
   */
  public Proyecto setNombreCorto(java.lang.String nombreCorto) {
    this.nombreCorto = nombreCorto;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public java.lang.String getNombreLargo() {
    return nombreLargo;
  }

  /**
   * @param nombreLargo nombreLargo or {@code null} for none
   */
  public Proyecto setNombreLargo(java.lang.String nombreLargo) {
    this.nombreLargo = nombreLargo;
    return this;
  }

  @Override
  public Proyecto set(String fieldName, Object value) {
    return (Proyecto) super.set(fieldName, value);
  }

  @Override
  public Proyecto clone() {
    return (Proyecto) super.clone();
  }

}
