/*
 * Licensed under the Apache License, Version 2.0 (the "License"); you may not use this file except
 * in compliance with the License. You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software distributed under the License
 * is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express
 * or implied. See the License for the specific language governing permissions and limitations under
 * the License.
 */
/*
 * This code was generated by https://code.google.com/p/google-apis-client-generator/
 * (build: 2014-11-17 18:43:33 UTC)
 * on 2015-01-10 at 02:56:28 UTC 
 * Modify at your own risk.
 */

package com.csgit.cao.model.communicationchannel.model;

/**
 * Model definition for Reportsmodel.
 *
 * <p> This is the Java data model class that specifies how to parse/serialize into the JSON that is
 * transmitted over HTTP when working with the communicationchannel. For a detailed explanation see:
 * <a href="http://code.google.com/p/google-http-java-client/wiki/JSON">http://code.google.com/p/google-http-java-client/wiki/JSON</a>
 * </p>
 *
 * @author Google, Inc.
 */
@SuppressWarnings("javadoc")
public final class Reportsmodel extends com.google.api.client.json.GenericJson {

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key("anticipo_Contrato")
  private java.lang.Double anticipoContrato;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key("avance_Financiero_Reportado")
  private java.lang.Double avanceFinancieroReportado;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key("avance_Fisico_Reportado")
  private java.lang.Double avanceFisicoReportado;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key("conveio_Numero")
  private java.lang.String conveioNumero;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key("direccion_Adscipcion")
  private java.lang.String direccionAdscipcion;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key("fecha_Contrato")
  private java.lang.String fechaContrato;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key("fecha_Convenio")
  private java.lang.String fechaConvenio;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key("fecha_Inicio")
  private java.lang.String fechaInicio;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key("fecha_Termino")
  private java.lang.String fechaTermino;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key @com.google.api.client.json.JsonString
  private java.util.List<java.lang.Long> idConceptos;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key @com.google.api.client.json.JsonString
  private java.lang.Long idConsecutivo;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key("idEmpresa_Comtratista") @com.google.api.client.json.JsonString
  private java.lang.Long idEmpresaComtratista;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key @com.google.api.client.json.JsonString
  private java.util.List<java.lang.Long> idMultimedia;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key @com.google.api.client.json.JsonString
  private java.lang.Long idObra;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key @com.google.api.client.json.JsonString
  private java.lang.Long idProyecto;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key @com.google.api.client.json.JsonString
  private java.lang.Long idReporte;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key @com.google.api.client.json.JsonString
  private java.lang.Long idubicacion;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key("importe_Acunulado")
  private java.lang.Double importeAcunulado;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key("importe_Contrato")
  private java.lang.Double importeContrato;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key("importe_Convenio")
  private java.lang.Double importeConvenio;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key("nombre_Contrato")
  private java.lang.String nombreContrato;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key("numero_Contrato")
  private java.lang.String numeroContrato;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key("numero_informe")
  private java.lang.String numeroInforme;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key("periodo_Ejecucion")
  private java.lang.Integer periodoEjecucion;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key("residente_Obra")
  private java.lang.String residenteObra;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key("saldo_Contrato")
  private java.lang.Double saldoContrato;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key("supervisor_Obra")
  private java.lang.String supervisorObra;

  /**
   * @return value or {@code null} for none
   */
  public java.lang.Double getAnticipoContrato() {
    return anticipoContrato;
  }

  /**
   * @param anticipoContrato anticipoContrato or {@code null} for none
   */
  public Reportsmodel setAnticipoContrato(java.lang.Double anticipoContrato) {
    this.anticipoContrato = anticipoContrato;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public java.lang.Double getAvanceFinancieroReportado() {
    return avanceFinancieroReportado;
  }

  /**
   * @param avanceFinancieroReportado avanceFinancieroReportado or {@code null} for none
   */
  public Reportsmodel setAvanceFinancieroReportado(java.lang.Double avanceFinancieroReportado) {
    this.avanceFinancieroReportado = avanceFinancieroReportado;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public java.lang.Double getAvanceFisicoReportado() {
    return avanceFisicoReportado;
  }

  /**
   * @param avanceFisicoReportado avanceFisicoReportado or {@code null} for none
   */
  public Reportsmodel setAvanceFisicoReportado(java.lang.Double avanceFisicoReportado) {
    this.avanceFisicoReportado = avanceFisicoReportado;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public java.lang.String getConveioNumero() {
    return conveioNumero;
  }

  /**
   * @param conveioNumero conveioNumero or {@code null} for none
   */
  public Reportsmodel setConveioNumero(java.lang.String conveioNumero) {
    this.conveioNumero = conveioNumero;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public java.lang.String getDireccionAdscipcion() {
    return direccionAdscipcion;
  }

  /**
   * @param direccionAdscipcion direccionAdscipcion or {@code null} for none
   */
  public Reportsmodel setDireccionAdscipcion(java.lang.String direccionAdscipcion) {
    this.direccionAdscipcion = direccionAdscipcion;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public java.lang.String getFechaContrato() {
    return fechaContrato;
  }

  /**
   * @param fechaContrato fechaContrato or {@code null} for none
   */
  public Reportsmodel setFechaContrato(java.lang.String fechaContrato) {
    this.fechaContrato = fechaContrato;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public java.lang.String getFechaConvenio() {
    return fechaConvenio;
  }

  /**
   * @param fechaConvenio fechaConvenio or {@code null} for none
   */
  public Reportsmodel setFechaConvenio(java.lang.String fechaConvenio) {
    this.fechaConvenio = fechaConvenio;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public java.lang.String getFechaInicio() {
    return fechaInicio;
  }

  /**
   * @param fechaInicio fechaInicio or {@code null} for none
   */
  public Reportsmodel setFechaInicio(java.lang.String fechaInicio) {
    this.fechaInicio = fechaInicio;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public java.lang.String getFechaTermino() {
    return fechaTermino;
  }

  /**
   * @param fechaTermino fechaTermino or {@code null} for none
   */
  public Reportsmodel setFechaTermino(java.lang.String fechaTermino) {
    this.fechaTermino = fechaTermino;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public java.util.List<java.lang.Long> getIdConceptos() {
    return idConceptos;
  }

  /**
   * @param idConceptos idConceptos or {@code null} for none
   */
  public Reportsmodel setIdConceptos(java.util.List<java.lang.Long> idConceptos) {
    this.idConceptos = idConceptos;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public java.lang.Long getIdConsecutivo() {
    return idConsecutivo;
  }

  /**
   * @param idConsecutivo idConsecutivo or {@code null} for none
   */
  public Reportsmodel setIdConsecutivo(java.lang.Long idConsecutivo) {
    this.idConsecutivo = idConsecutivo;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public java.lang.Long getIdEmpresaComtratista() {
    return idEmpresaComtratista;
  }

  /**
   * @param idEmpresaComtratista idEmpresaComtratista or {@code null} for none
   */
  public Reportsmodel setIdEmpresaComtratista(java.lang.Long idEmpresaComtratista) {
    this.idEmpresaComtratista = idEmpresaComtratista;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public java.util.List<java.lang.Long> getIdMultimedia() {
    return idMultimedia;
  }

  /**
   * @param idMultimedia idMultimedia or {@code null} for none
   */
  public Reportsmodel setIdMultimedia(java.util.List<java.lang.Long> idMultimedia) {
    this.idMultimedia = idMultimedia;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public java.lang.Long getIdObra() {
    return idObra;
  }

  /**
   * @param idObra idObra or {@code null} for none
   */
  public Reportsmodel setIdObra(java.lang.Long idObra) {
    this.idObra = idObra;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public java.lang.Long getIdProyecto() {
    return idProyecto;
  }

  /**
   * @param idProyecto idProyecto or {@code null} for none
   */
  public Reportsmodel setIdProyecto(java.lang.Long idProyecto) {
    this.idProyecto = idProyecto;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public java.lang.Long getIdReporte() {
    return idReporte;
  }

  /**
   * @param idReporte idReporte or {@code null} for none
   */
  public Reportsmodel setIdReporte(java.lang.Long idReporte) {
    this.idReporte = idReporte;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public java.lang.Long getIdubicacion() {
    return idubicacion;
  }

  /**
   * @param idubicacion idubicacion or {@code null} for none
   */
  public Reportsmodel setIdubicacion(java.lang.Long idubicacion) {
    this.idubicacion = idubicacion;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public java.lang.Double getImporteAcunulado() {
    return importeAcunulado;
  }

  /**
   * @param importeAcunulado importeAcunulado or {@code null} for none
   */
  public Reportsmodel setImporteAcunulado(java.lang.Double importeAcunulado) {
    this.importeAcunulado = importeAcunulado;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public java.lang.Double getImporteContrato() {
    return importeContrato;
  }

  /**
   * @param importeContrato importeContrato or {@code null} for none
   */
  public Reportsmodel setImporteContrato(java.lang.Double importeContrato) {
    this.importeContrato = importeContrato;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public java.lang.Double getImporteConvenio() {
    return importeConvenio;
  }

  /**
   * @param importeConvenio importeConvenio or {@code null} for none
   */
  public Reportsmodel setImporteConvenio(java.lang.Double importeConvenio) {
    this.importeConvenio = importeConvenio;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public java.lang.String getNombreContrato() {
    return nombreContrato;
  }

  /**
   * @param nombreContrato nombreContrato or {@code null} for none
   */
  public Reportsmodel setNombreContrato(java.lang.String nombreContrato) {
    this.nombreContrato = nombreContrato;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public java.lang.String getNumeroContrato() {
    return numeroContrato;
  }

  /**
   * @param numeroContrato numeroContrato or {@code null} for none
   */
  public Reportsmodel setNumeroContrato(java.lang.String numeroContrato) {
    this.numeroContrato = numeroContrato;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public java.lang.String getNumeroInforme() {
    return numeroInforme;
  }

  /**
   * @param numeroInforme numeroInforme or {@code null} for none
   */
  public Reportsmodel setNumeroInforme(java.lang.String numeroInforme) {
    this.numeroInforme = numeroInforme;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public java.lang.Integer getPeriodoEjecucion() {
    return periodoEjecucion;
  }

  /**
   * @param periodoEjecucion periodoEjecucion or {@code null} for none
   */
  public Reportsmodel setPeriodoEjecucion(java.lang.Integer periodoEjecucion) {
    this.periodoEjecucion = periodoEjecucion;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public java.lang.String getResidenteObra() {
    return residenteObra;
  }

  /**
   * @param residenteObra residenteObra or {@code null} for none
   */
  public Reportsmodel setResidenteObra(java.lang.String residenteObra) {
    this.residenteObra = residenteObra;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public java.lang.Double getSaldoContrato() {
    return saldoContrato;
  }

  /**
   * @param saldoContrato saldoContrato or {@code null} for none
   */
  public Reportsmodel setSaldoContrato(java.lang.Double saldoContrato) {
    this.saldoContrato = saldoContrato;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public java.lang.String getSupervisorObra() {
    return supervisorObra;
  }

  /**
   * @param supervisorObra supervisorObra or {@code null} for none
   */
  public Reportsmodel setSupervisorObra(java.lang.String supervisorObra) {
    this.supervisorObra = supervisorObra;
    return this;
  }

  @Override
  public Reportsmodel set(String fieldName, Object value) {
    return (Reportsmodel) super.set(fieldName, value);
  }

  @Override
  public Reportsmodel clone() {
    return (Reportsmodel) super.clone();
  }

}
