/*
 * Licensed under the Apache License, Version 2.0 (the "License"); you may not use this file except
 * in compliance with the License. You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software distributed under the License
 * is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express
 * or implied. See the License for the specific language governing permissions and limitations under
 * the License.
 */
/*
 * This code was generated by https://code.google.com/p/google-apis-client-generator/
 * (build: 2014-11-17 18:43:33 UTC)
 * on 2015-01-10 at 02:56:28 UTC 
 * Modify at your own risk.
 */

package com.csgit.cao.model.communicationchannel.model;

/**
 * Model definition for ReporteDiario.
 *
 * <p> This is the Java data model class that specifies how to parse/serialize into the JSON that is
 * transmitted over HTTP when working with the communicationchannel. For a detailed explanation see:
 * <a href="http://code.google.com/p/google-http-java-client/wiki/JSON">http://code.google.com/p/google-http-java-client/wiki/JSON</a>
 * </p>
 *
 * @author Google, Inc.
 */
@SuppressWarnings("javadoc")
public final class ReporteDiario extends com.google.api.client.json.GenericJson {

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.lang.Integer clave;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.lang.String email;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.lang.String fechaReporteDiario;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key @com.google.api.client.json.JsonString
  private java.lang.Long idDispo;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key("id_Minuta") @com.google.api.client.json.JsonString
  private java.lang.Long idMinuta;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key("id_Notas") @com.google.api.client.json.JsonString
  private java.lang.Long idNotas;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key("id_Obra") @com.google.api.client.json.JsonString
  private java.lang.Long idObra;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key("id_RMaquinariaEquipo") @com.google.api.client.json.JsonString
  private java.lang.Long idRMaquinariaEquipo;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key("id_RPersonal") @com.google.api.client.json.JsonString
  private java.lang.Long idRPersonal;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key("id_ReporteDiario") @com.google.api.client.json.JsonString
  private java.lang.Long idReporteDiario;

  /**
   * @return value or {@code null} for none
   */
  public java.lang.Integer getClave() {
    return clave;
  }

  /**
   * @param clave clave or {@code null} for none
   */
  public ReporteDiario setClave(java.lang.Integer clave) {
    this.clave = clave;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public java.lang.String getEmail() {
    return email;
  }

  /**
   * @param email email or {@code null} for none
   */
  public ReporteDiario setEmail(java.lang.String email) {
    this.email = email;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public java.lang.String getFechaReporteDiario() {
    return fechaReporteDiario;
  }

  /**
   * @param fechaReporteDiario fechaReporteDiario or {@code null} for none
   */
  public ReporteDiario setFechaReporteDiario(java.lang.String fechaReporteDiario) {
    this.fechaReporteDiario = fechaReporteDiario;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public java.lang.Long getIdDispo() {
    return idDispo;
  }

  /**
   * @param idDispo idDispo or {@code null} for none
   */
  public ReporteDiario setIdDispo(java.lang.Long idDispo) {
    this.idDispo = idDispo;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public java.lang.Long getIdMinuta() {
    return idMinuta;
  }

  /**
   * @param idMinuta idMinuta or {@code null} for none
   */
  public ReporteDiario setIdMinuta(java.lang.Long idMinuta) {
    this.idMinuta = idMinuta;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public java.lang.Long getIdNotas() {
    return idNotas;
  }

  /**
   * @param idNotas idNotas or {@code null} for none
   */
  public ReporteDiario setIdNotas(java.lang.Long idNotas) {
    this.idNotas = idNotas;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public java.lang.Long getIdObra() {
    return idObra;
  }

  /**
   * @param idObra idObra or {@code null} for none
   */
  public ReporteDiario setIdObra(java.lang.Long idObra) {
    this.idObra = idObra;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public java.lang.Long getIdRMaquinariaEquipo() {
    return idRMaquinariaEquipo;
  }

  /**
   * @param idRMaquinariaEquipo idRMaquinariaEquipo or {@code null} for none
   */
  public ReporteDiario setIdRMaquinariaEquipo(java.lang.Long idRMaquinariaEquipo) {
    this.idRMaquinariaEquipo = idRMaquinariaEquipo;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public java.lang.Long getIdRPersonal() {
    return idRPersonal;
  }

  /**
   * @param idRPersonal idRPersonal or {@code null} for none
   */
  public ReporteDiario setIdRPersonal(java.lang.Long idRPersonal) {
    this.idRPersonal = idRPersonal;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public java.lang.Long getIdReporteDiario() {
    return idReporteDiario;
  }

  /**
   * @param idReporteDiario idReporteDiario or {@code null} for none
   */
  public ReporteDiario setIdReporteDiario(java.lang.Long idReporteDiario) {
    this.idReporteDiario = idReporteDiario;
    return this;
  }

  @Override
  public ReporteDiario set(String fieldName, Object value) {
    return (ReporteDiario) super.set(fieldName, value);
  }

  @Override
  public ReporteDiario clone() {
    return (ReporteDiario) super.clone();
  }

}
