/*
 * Licensed under the Apache License, Version 2.0 (the "License"); you may not use this file except
 * in compliance with the License. You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software distributed under the License
 * is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express
 * or implied. See the License for the specific language governing permissions and limitations under
 * the License.
 */
/*
 * This code was generated by https://code.google.com/p/google-apis-client-generator/
 * (build: 2014-11-17 18:43:33 UTC)
 * on 2015-01-10 at 02:56:28 UTC 
 * Modify at your own risk.
 */

package com.csgit.cao.model.communicationchannel.model;

/**
 * Model definition for Ubicaciones.
 *
 * <p> This is the Java data model class that specifies how to parse/serialize into the JSON that is
 * transmitted over HTTP when working with the communicationchannel. For a detailed explanation see:
 * <a href="http://code.google.com/p/google-http-java-client/wiki/JSON">http://code.google.com/p/google-http-java-client/wiki/JSON</a>
 * </p>
 *
 * @author Google, Inc.
 */
@SuppressWarnings("javadoc")
public final class Ubicaciones extends com.google.api.client.json.GenericJson {

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key("id_Ubicacion") @com.google.api.client.json.JsonString
  private java.lang.Long idUbicacion;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.util.List<java.lang.String> ubicacion;

  /**
   * @return value or {@code null} for none
   */
  public java.lang.Long getIdUbicacion() {
    return idUbicacion;
  }

  /**
   * @param idUbicacion idUbicacion or {@code null} for none
   */
  public Ubicaciones setIdUbicacion(java.lang.Long idUbicacion) {
    this.idUbicacion = idUbicacion;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public java.util.List<java.lang.String> getUbicacion() {
    return ubicacion;
  }

  /**
   * @param ubicacion ubicacion or {@code null} for none
   */
  public Ubicaciones setUbicacion(java.util.List<java.lang.String> ubicacion) {
    this.ubicacion = ubicacion;
    return this;
  }

  @Override
  public Ubicaciones set(String fieldName, Object value) {
    return (Ubicaciones) super.set(fieldName, value);
  }

  @Override
  public Ubicaciones clone() {
    return (Ubicaciones) super.clone();
  }

}
